<<<<<<< HEAD
sonar.projectKey=Jayquio_flutterQRwDB
=======
sonar.projectKey=Jayquio_inventoryQR
>>>>>>> 615cb54d32e9fd4d94e3503af8aab7c76e53567d
sonar.organization=jayquio

sonar.sources=lib
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
